### PR TITLE
Add config setting to disable tool and armor durability

### PR DESCRIPTION
**Pull request by chrisjanusa**
Tested this on 1.19.4 and it worked for both tools and armor
Tested that the "This boat has legs" achievement is still obtainable

Let me know any other scenarios you want me to test
image
image

### CODE REVIEW

**Comment by Steaf23** [comment]
I was thinking maybe instead of making it a config option it can be a setting in the settings menu, this is quite a bit of work so let me know if you are up for it

**Comment by chrisjanusa** [comment]
Yea I should be able to do that

**Comment by chrisjanusa** [comment]
@Steaf23 I moved it into the Player Effects section. Just let me know if you think there is a better home for it in the settings menus though.

**Comment by chrisjanusa** [comment]
Also I refactored the player effects menu a little so if you don't like any of the changes I made just let me know and I will revert them.

**Pull request merged**
